### ISSUE TITLE
some questions on data.json

### ISSUE THREAD

**Issue by Torah** [anantnema/3DModelReactJs#1]
Hi,

I saw data.json in this project and I am confused about two questions. First, how you upload your model files and store them? Second, only one png for every model?

**Comment by anantnema** [comment]
hi @Torah , 

1) Model is an array of an object which contains 4 things: name, thumbnail image, .obj file and .mtl file.
name is to give the name of an animal or object,
thumbnail image is to show the image on the list,
.obj file to give the structure of animal or object,
.mtl file to give the materialistic feature to the outlined structure by .obj file,
It is stored in AWS. 

2) yes only one png for every model, rest 3d object is generated using .obj and .mtl files.

**Comment by Torah** [comment]
Hi, 

thank you for your reply!
I am now considering to build a personal server for store and search 3D model project files similar to Thingiverse. Searched for a well to find a Thingiverse-ish opensource web framework but I failed. Personally I think your this project can be changed to fulfill this aim, but some revise should be made to accomplish some basic functions like:
1、a button to push projects like Github or Gitlab
2、more png window for one 3D project
3、a search input
and I think openscad project may be useful for this kind of project. Since I am family with python rather than ReactJS, I think those rebuild may be cost of time, although this project maybe valuable for 3D machine user (The speed for searching Thinkiverse is not enough and no opensource webframe for 3D model projects' files available)
